GreatKidsFarm/config/routes.rb
Rails.application.routes.draw do

  resources :reports, :projects, :galleries
  get 'report/index'
  get 'report/download'
  get 'report/images'
  get 'report/acknowledgement'
  get 'report/overview'
  get 'report/farm_wide'
  get 'report/greenhouse_3'
  get 'report/estimated_costs'
  get 'report/greenhouse_1_costs'
  get 'report/greenhouse_2_costs'
  get 'report/greenhouse_3_costs'
  get 'report/total_costs'
  get 'report/demonstration_projects'
  get 'report/calculations'

  root 'report#overview'

end

GreatKidsFarm/app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment :image, content_type: { :content_type => /\Aimage\/.*\Z/ }
end

GreatKidsFarm/app/models/project.rb
class Project < ActiveRecord::Base
  has_many :proposals
end

GreatKidsFarm/app/models/proposal.rb
class Proposal < ActiveRecord::Base
  belongs_to :project
end

GreatKidsFarm/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

GreatKidsFarm/app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController

  def index
    @galleries = Gallery.all
  end

  def show
    @gallery = Gallery.find(params[:id])
  end

  def new
    @gallery = Gallery.new
  end

  def create
    @gallery = Gallery.create gallery_params
    if @gallery.save
      redirect_to action: 'index'
    else
      render 'new'
    end
  end

  private
  def gallery_params
    params.require(:gallery).permit(:image, :title, :caption)
  end
end

GreatKidsFarm/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end
end

GreatKidsFarm/app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end
end

GreatKidsFarm/app/controllers/report_controller.rb
class ReportController < ApplicationController
  def index
    @images = Dir.glob("app/assets/images/slider/*.png")
  end

  def acknowledgement
    render 'acknowledgement'
  end

  def download
    send_file 'Great_Kids_Farm-Elysian_Energy.pdf', type: 'application/pdf', x_sendfile: true
  end

  def images
    @images = Dir.glob("app/assets/images/slider/*.png")
  end

end

GreatKidsFarm/app/helpers/application_helper.rb
module ApplicationHelper
end

GreatKidsFarm/app/helpers/galleries_helper.rb
module GalleriesHelper
end

GreatKidsFarm/app/helpers/projects_helper.rb
module ProjectsHelper
end

GreatKidsFarm/app/helpers/proposals_helper.rb
module ProposalsHelper
end

GreatKidsFarm/app/helpers/report_helper.rb
module ReportHelper
end

GreatKidsFarm/app/views/galleries/index.html.erb
<h1>Gallery</h1>
</br>

<script>
  Galleria.run('.galleria')
</script>

<div class="galleria">
    <% @galleries.each do |picture| %>
      <%= image_tag (picture.image.url), title: picture.caption %>
    <% end %>
</div>

GreatKidsFarm/app/views/galleries/new.html.erb
<h1>Add an image to the gallery</h1>
<%= simple_form_for @gallery, html: { multipart: true } do |f| %>
  <%= f.input :title %>
  <%= f.input :caption %>
  <%= f.input :image, as: :file %>

  <%= f.button :submit %>
<% end %>

GreatKidsFarm/app/views/galleries/show.html.erb
<p>
    <strong>Image:</strong>
    <%= image_tag @gallery.image.url(:large) %>
</p>

GreatKidsFarm/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GreatKidsFarm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,700,300italic,400italic,700italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid main-container">
  <%= render '/navbar' %>
  <div class="container content-container">
    <div class="row">
      <%= image_tag("Great_Kids_Farm.jpg", class: "img-responsive head-image") %>
      <div class="col-md-10 col-md-offset-1">
        <%= yield %>
      </div>
    </div>
  </div>
</div>

</body>
</html>

GreatKidsFarm/app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

GreatKidsFarm/app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

GreatKidsFarm/app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

GreatKidsFarm/app/views/projects/index.html.erb
<h1>Projects#index</h1>
<p>Find me in app/views/projects/index.html.erb</p>

GreatKidsFarm/app/views/projects/new.html.erb
<h1>Projects#new</h1>
<p>Find me in app/views/projects/new.html.erb</p>

GreatKidsFarm/app/views/projects/show.html.erb
<h1>Projects#show</h1>
<p>Find me in app/views/projects/show.html.erb</p>

GreatKidsFarm/app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>

GreatKidsFarm/app/views/proposals/create.html.erb
<h1>Proposals#create</h1>
<p>Find me in app/views/proposals/create.html.erb</p>

GreatKidsFarm/app/views/proposals/destroy.html.erb
<h1>Proposals#destroy</h1>
<p>Find me in app/views/proposals/destroy.html.erb</p>

GreatKidsFarm/app/views/proposals/edit.html.erb
<h1>Proposals#edit</h1>
<p>Find me in app/views/proposals/edit.html.erb</p>

GreatKidsFarm/app/views/proposals/index.html.erb
<h1>Proposals#index</h1>
<p>Find me in app/views/proposals/index.html.erb</p>

GreatKidsFarm/app/views/proposals/new.html.erb
<h1>Proposals#new</h1>
<p>Find me in app/views/proposals/new.html.erb</p>

GreatKidsFarm/app/views/proposals/show.html.erb
<h1>Proposals#show</h1>
<p>Find me in app/views/proposals/show.html.erb</p>

GreatKidsFarm/app/views/proposals/update.html.erb
<h1>Proposals#update</h1>
<p>Find me in app/views/proposals/update.html.erb</p>

GreatKidsFarm/app/views/report/_acknowledgement.html.erb
<h1>Acknowledgements</h1>
<p>Many thanks are due to the people who shared their time, passion and expertise informing this report including:</p>
<ul>
  <li>The staff at Great Kids Farm – Chrissa, Brooks and Beth were all very generous with their time and information.</li>
  <li>Ed Snodgrass and Dominique Bayne of Emory Knolls Farm shared their decades of experience and lessons learned, particularly regarding the greenhouse glazing as well as heating and ventilation strategies.</li>
  <li>Jim Franklin of Maryland Plants and Supplies provided advisement on material pricing as well as heating and ventilation strategies.</li>
  <li>Barry Cullen and Matt Tao of Luther Contracting consulted on the durability of Greenhouse 3 and Head house, particularly regarding the masonry and roof.</li>
  <li>Andrew Truitt of Truitt Renewable Energy Consulting provided insights on solar thermal and solar photovoltaics.</li>
  <a name="overview"></a><li>Todd Humora (Electrical Engineer) advised on automating controls.</li>
</ul>

GreatKidsFarm/app/views/report/_demonstration_table.html.erb
<table class="table">
  <thead>
    <th>Project</th>
    <th>Intention</th>
    <th class="text-right">Est. Cost</th>
  </thead>
  <body>
    <tr>
      <td rowspan="2">Green Roof</td>
      <td>Option 1: Replace with polyethylene</td>
      <td class="text-right">$4,800</td>
    </tr>
    <tr>
      <td>Option 2: Replace with polycarbonate</td>
      <td class="text-right">$1,400</td>
    </tr>
    <tr>
      <td>Solar Hot Water</td>
      <td>Repair install</td>
      <td class="text-right">$9,000</td>
    </tr>
    <tr>
      <td>Solar Photovoltaics (4kW System)</td>
      <td>Install</td>
      <td class="text-right">$16,000</td>
    </tr>
    <tr>
      <td>Interactive Website</td>
      <td>Install subpanel</td>
      <td class="text-right">$4,700</td>
    </tr>
    <tr>
      <th colspan="2">Demonstration Projects Potential Costs</th>
      <th class="text-right">$35,900</th>
    </tr>
  </body>
</table>

GreatKidsFarm/app/views/report/_estimated_costs.html.erb
<h1>Estimated Costs</h1>
<p>Before undertaking any improvements GKF or its contractors will need to contact Miss Utility to locate underground utility lines and pipes. Once attained, these records must be filed at GKF and with BPS.</p>

<%= render 'gh1_table' %>
<%= render 'gh2_table' %>
<%= render 'gh3_table' %>

GreatKidsFarm/app/views/report/_executive_summary.html.erb
<h1>Overview</h1>
<h2>Executive Summary</h2>
<p>Great Kids Farm (GKF) is a working farm used to educate “students of all ages about healthy eating, sustainable agriculture and the natural sciences.” Elysian Energy, LLC was retained by Friends of Great Kids Farm to provide advisement for improving three existing greenhouses at Great Kids Farm to expand their utility, efficiency and production capacity. Greenhouse One (GH1) is currently the primary greenhouse for GKF while Greenhouse Two (GH2) is used sparingly.  Currently GKF uses these greenhouses to produce micro-greens for sale to restaurants as well as seedlings for planting on the farm and distribution to school gardens. Greenhouse Three and adjacent Head House (GH3) is in significant disrepair and unusable.</p>
<p>The evaluative criteria included safety, durability, usability, energy efficiency and production capacity.  </p>
<p>All of the greenhouses require significant improvements to restore functionally reliable, year-round production and building safety. We recommend the following improvements.</p>
<ul>
  <li>Identify and map electrical, natural gas and water service lines</li>
  <li>Replace all plate glass glazing</li>
  <li>Upgrade heating and ventilation systems</li>
  <li>Improve electrical systems</li>
  <li>Implement backup generator(s)</li>
  <li>Add controls to monitor and remotely control critical functions</li>
  <li>Improve windows (GH3) and doors (GH1, GH2 and GH3)</li>
</ul>
<p>Greenhouse 3 requires additional significant structural and functional improvements.</p>
<h3>GH3 Structural</h3>
<ul>
  <li>Comprehensive masonry repair to Head House and foundation walls of green house</li>
  <li>Repairs to cinder block supports of tables in green house</li>
  <li>New roof on head house</li>
</ul>
<h3>GH3 Functional</h3>
<ul>
  <li>Renovate restroom</li>
  <li>New water heater</li>
  <li>New utility sink</li>
  <li>New garage door</li>
  <li>New refrigeration unit</li>
  <li>Install preparation, storage and staging areas for transfer</li>
</ul>
<p>Additional consideration and research was performed for the following demonstration projects:</p>
<ul>
  <li>Green roofs</li>
  <li>Solar heating</li>
  <li>Solar electricity</li>
  <li>Interactive, educational website</li>
</ul>
<h2>Additional Considerations</h2>
<ol>
  <li>We were unable to calculate energy intensity for the Greenhouses because available utility data included the administrative building, which is outside the scope of this report.</li>
  <li>The recommendations in this report are based on good/better/best opportunities incorporating information from GKF site staff, publicly available best practices, interviews with leaders in the field, as well as financial considerations.</li>
  <li>Maryland has a robust incentive landscape for ECMs.  The electric utility that serves Great Kids Farm, BGE, has significant incentives for lighting, HVAC and refrigeration. These incentives were not included for several reasons:</li>
  <ol>
    <li>Specificity. BGE does not guarantee a specific incentive amount until their engineers review projects and issue a rebate reservation letter.</li>
    <li>Funding.  BGE’s programs, while well funded when compared to other states’ programs, are not unlimited, and funds are reserved on a first-come, first-served basis.</li>
    <li>Timeliness. The rebate reservation letter only reserves the rebates for 6 months before they expire.  Depending on which projects make the most sense, delaying the submission of project details to BGE will likely sync timelines so that GKF doesn’t need to reapply.</li>
  </ol>
  <li>Additional sources of funding may be available from the Maryland Energy Administration.  Two programs of note:</li>
  <ol>
    <li><%= link_to 'Jane E. Lawton Conservation Loan Program', 'http://energy.maryland.gov/Govt/janeelawton.html', target: '_blank' %></li>
    <li><%= link_to 'Kathleen A.P. Mathias Agriculture Energy Efficiency Program', 'http://energy.maryland.gov/Business/MathiasAg14.htm', target: '_blank' %> (contact Dean Fisher at 410-260-2605)</li>
  </ol>
</ol>
<p>Lastly, and most importantly, Great Kids Farm has an extraordinary opportunity to nurture healthy and successful Baltimore City School students to be healthy and productive members of society. It’s a meaningful task—nearly one in four Baltimore’s school-age children live in a food desert.  The pages that follow include improvements to the physical spaces that will be able to host not only additional production of plants but also additional or enhanced programming for the students. While programming is outside the scope of this physical needs assessment, the opportunities at the intersection of improving the greenhouses and improved/expanded programming experiences are many.  Expanded uses for the greenhouses may include:</p>
<ul>
  <li>Year-round production</li>
  <li>Production of seedlings for distribution to school gardens including:</li>
  <ul>
    <li>Propagation of cuttings from GKF orchard and</li>
    <li>Distribution of other garden supports</li>
  </ul>
  <li>Greater skills practice opportunities for interns</li>
  <li>Aquaponics</li>
  <li>Remote monitoring of greenhouses by GKF staff</li>
  <li>Distance learning and continued student engagement via webinars, webcam feeds.</li>
</ul>

GreatKidsFarm/app/views/report/_gh1_equipment.html.erb
<h3>Greenhouse 1 Line Items</h3>
<table class="table table-striped">
  <thead>
    <th colspan="1">Item</th>
    <th class="text-right">Cost</th>
  </thead>
  <tbody>
    <th class="line-item" colspan="2">1. Glass Removal</th>
    <tr>
      <td>Glass removal</td>
      <td>$1,500 for labor, hauling and disposal.</td>
    </tr>
    <tr>
      <td rowspan="2">Frame prep</td>
      <td>$1,200 for labor</td>
    </tr>
    <tr>
      <td>$500 frame materials (to treat sharp edges)</td>
    </tr>
    <tr>
      <td rowspan="4">Polyethylene</td>
      <td><a href="https://www.growerssupply.com/farm/supplies/prod1;gs_greenhouse_films;pg109093.html">$1,400 for polyethylene greenhouse film [$1,000 / $400 for 4yr (i.e. roof) and 6 month (i.e. sidewall) polyethylene respectively]</a></td>
    </tr>
    <tr>
      <td><a href="https://www.growerssupply.com/farm/supplies/prod1;gs_greenhouse_films;pgqh1095.html">$400 for inflating blowers (2 @ $200 each)</a></td>
    </tr>
    <tr>
      <td>$600 for fastening systems</td>
    </tr>
    <tr>
      <td>$2,500 installation and commissioning labor</td>
    </tr>
    <tr>
      <td rowspan="4">Polycarbonate</td>
      <td><a href="http://www.growerssupply.com/farm/supplies/prod1;gs_greenhouse_polycarbonate;pg104618_111353.html
">$7,160 for polycarbonate panels</a></td>
    </tr>
    <tr>
      <td><a href="http://www.growerssupply.com/farm/supplies/prod1;gs_greenhouse_polycarbonate;pg107198G.html
">$1,200 for mounting extrusions</a></td>
    </tr>
    <tr>
      <td>$400 for mounting hardware</td>
    </tr>
    <tr>
      <td>$3,000 labor</td>
    </tr>
    <th class="line-item" colspan="2">2. Heating</th>
    <tr>
      <td rowspan="5">Heating</td>
      <td><a href="http://www.homedepot.com/b/Plumbing-Pipes-Fittings-PEX-Pipe-Fittings/N-5yc1vZbuty
">$1,400 for tubing and fittings</a></td>
    <tr>
      <td>$500 for pump and manifold</td>
    </tr>
    <tr>
      <td>$700 to set concrete forms</td>
    </tr>
    <tr>
      <td>$2,300 for concrete</td>
    </tr>
    <tr>
      <td>$1,400 for HVAC re-commissioning</td>
    </tr>

    <th class="line-item" colspan="2">3. Ventilation</th>
    <tr>
      <td rowspan="6">Ventilation</td>
      <td><a href="https://www.growerssupply.com/farm/supplies/cat1;gs_cooling_fans;gs_exhaust_fans.html
">$800 materials: two 24” fans with 7,000 cfm (or greater) capacity in N wall</a></td>
    </tr>
    <tr>  
      <td>$200 prep and buttress walls</td>
    </tr>
    <tr>  
      <td><a href="https://www.growerssupply.com/farm/supplies/cat1a;gs_shutters_vents_louvers_1.html
">$300 install additional shutter boxes on S wall</a></td>
    </tr>
    <tr>  
      <td>$550 electrical labor</td>
    </tr>
    <tr>  
      <td>$150 electrical materials</td>
    </tr>
    <tr>  
      <td>$200 remove old ventilation apparatus</td>
    </tr>
    <th class="line-item" colspan="2">4. Electrical</th>
    <tr>
      <td>Electrical</td>
      <td>$100 Labor to troubleshoot service panel and replace GH2 breaker for diagnostics if necessary</td>
    </tr>
    <th class="line-item" colspan="2">5. Generator</th>
    <tr>
      <td rowspan="2">Generator</td>
      <td> $4,500 for generator (200 Amp service to ensure GH1 and GH2 have electrical service during utility service interruptions)</td>
    </tr>
    <tr>
      <td>$1,500 installation labor</td>
    </tr>
    <th class="line-item" colspan="2">6. Lighting</th>
    <tr>
      <td rowspan="2">Lighting</td>
      <td>$100 materials</td>
    </tr>
    <tr>
      <td>$200 labor</td>
    </tr>
    <th class="line-item" colspan="2">7. Doors</th>
    <tr>
      <td rowspan="3">Doors</td>
      <td>$250 for new N-wall door</td>
    <tr>
      <td>$170 for closing mechanisms for N- and S-wall doors</td>
    </tr>
    <tr>
      <td>$380 Labor</td>
    </tr>
    <th class="line-item" colspan="2">8. Controls</th>
    <tr>
      <td rowspan="2">Controls</td>
      <td><a href="https://www.growerssupply.com/farm/supplies/prod1;gs_thermostats_controllers;pg111138.html
">$5,000 Sensors, controls, iGrow Greenhouse controller and software</a></td>
    </tr>
    <tr>
      <td>$2,500 for electrical engineering, installation and commissioning<br/>  [Please note this requires either a cellular or wireless internet subscription, adding $600 - $1,200 per year on an ongoing basis]</td> 
    </tr>
    <th class="line-item" colspan="2">9. Pricing</th>
    <tr>
      <td></td>
      <td>The cost of the tabletop encasement is shown in both prices.
</td>
    </tr>
  </tbody>
</table>

GreatKidsFarm/app/views/report/_gh2_equipment.html.erb
<h3>Greenhouse 2 Line Items</h3>
<table class="table table-striped">
  <thead>
    <th colspan="1">Item</th>
    <th class="text-right">Cost</th>
  </thead>
  <tbody>
    <th class="line-item" colspan="2">1. Glass Removal</th>
    <tr>
      <td>Glass removal</td>
      <td>$ 800 for labor, hauling and disposal.</td>
    </tr>
    <tr>
      <td rowspan="2">Frame prep</td>
      <td>$ 800 for labor</td>
    </tr>
    <tr>
      <td>$ 300 frame materials (to treat sharp edges)</td>
    </tr>
    <tr>
      <td rowspan="4">Polyethylene  </td>
      <td>$ 900 for polyethylene greenhouse film [$700 / $200 for 4yr (i.e. roof) and 6 month (i.e. sidewall) polyethylene respectively]</td>
    </tr>
    <tr>  
      <td>$ 400 for inflating blowers (2 @ $200 each)</td>
    </tr>
    <tr>  
      <td>$ 400 for fastening systems</td>
    </tr>
    <tr>
      <td>$1,900 installation and commissioning</td>
    </tr>
    <tr>
      <td rowspan="4">Polycarbonate</td>
      <td>$5,400 for polycarbonate panels</td>
    </tr>
    <tr>
      <td>$800 for mounting extrusions</td>
    </tr>
    <tr>
      <td>$200 for mounting hardware</td>
    </tr>
    <tr>
      <td>$2,200 labor</td>
    </tr>
    <th class="line-item" colspan="2">2. Heating</th>
    <tr>
      <td rowspan="3">Option I</td>
      <td>$ 2,000 for trenching and finding the leak</td>
    </tr>
    <tr>
      <td>$600 for replacing the pipe</td>
    </tr>
    <tr>
      <td>$200 for backfilling</td>
    </tr>
    <tr>
      <td rowspan="2">Option 2</td>
      <td>$ 4,000 for 83.8% efficient Weil McClain boiler</td>
    </tr>
    <tr>
      <td>$2,400 gas fitting and labor</td>
    </tr>
    <tr>
      <td rowspan="5">Option 3</td>
      <td>$600 for tubing and fittings</td>
    </tr>
    <tr>
      <td>$500 for pump and manifold</td>
    </tr>
    <tr>
      <td>$400 to set concrete forms</td>
    </tr>
    <tr>
      <td>$800 for concrete</td>
    </tr>
    <tr>
      <td>$1,000 for HVAC re-commissioning</td>
    </tr>
    <th class="line-item" colspan="2">3. Ventilation</th>
    <tr>
      <td rowspan="6">Ventilation</td>
      <td>$400 materials: one 24” fan with 6,000 cfm (or greater) capacity in N wall</td>
    </tr>
    <tr>
      <td>$200 prep and buttress walls</td>
    </tr>
    <tr>
      <td>$150 install additional shutter box on S wall</td>
    </tr>
    <tr>
      <td>$300 electrical labor</td>
    </tr>
    <tr>
      <td>$50 electrical materials</td>
    </tr>
    <tr>
      <td>$100 remove old ventilation apparatus</td>
    </tr>
    <th class="line-item" colspan="2">4. Electrical</th>
    <tr>
      <td>Electrical</td>
      <td>$1,600 for subpanel in/for GH2 if needed based on GH1 panel examination</td>
    </tr>
    <th class="line-item" colspan="2">5. Lighting</th>
    <tr>
      <td rowspan="2">Lighting</td>
      <td>$40 materials</td>
    </tr>
    <tr>
      <td>$60 labor</td>
    </tr>
    <th class="line-item" colspan="2">6. Doors</th>
    <tr>
      <td rowspan="3">Doors</td>
      <td>$400 for doors</td>
    </tr>
    <tr>
      <td>$170 for closing mechanisms</td>
    </tr>
    <tr>
      <td>$380 for labor</td>
    </tr>
    <th class="line-item" colspan="2">7. Pricing</th>
    <tr>
      <td>Pricing</td>
      <td>The cost of the tabletop encasement is shown in both prices.</td>
    </tr>
  </tbody>
</table>

GreatKidsFarm/app/views/report/_gh2_table.html.erb
<h3>Greenhouse 2</h3>
<table class="table table-striped">
  <thead>
    <th colspan="2">Greenhouse 2 Improvements</th>
    <th class="text-right">Est. Cost</th>
  </thead>
  <tbody>
    <tr>
      <td rowspan="2">Replace plate glass</td>
      <td>Option 1: Replace with Polyethylene</td>
      <td class="text-right">$5,700</td>
    </tr>
    <tr>
      <td>Option 2: Replace with Polycarbonate</td>
      <td class="text-right">$10,500</td>
    </tr>
    <tr>
      <td rowspan="3">Heating</td>
      <td>Option 1: Repair and install pipe</td>
      <td class="text-right">$2,800</td>
    </tr>
    <tr>
      <td>Option 2: Repair and install a boiler</td>
      <td class="text-right">$6,400</td>
    </tr>
    <tr>
      <td>*Convert to encased tabletop</td>
      <td class="text-right">$4,400</td>
    </tr>
    <tr>
      <td>Ventilation</td>
      <td>Install</td>
      <td class="text-right">$1,200</td>
    </tr>
    <tr>
      <td>Electrical</td>
      <td>Install subpanel</td>
      <td class="text-right">$1,600</td>
    </tr>
    <tr>
      <td>Back-up Generator</td>
      <td>Ensure power to avoid crop failure</td>
      <td class="text-right">$5,000</td>
    </tr>
    <tr>
      <td rowspan="2">Doors</td>
      <td>Replace</td>
      <td class="text-right">$200</td>
    </tr>
    <tr>
      <td>Install for GH1 and GH2</td>
      <td class="text-right">$1,000</td>
    </tr>
    <tr>
      <th>Greenhouse 2 Total Estimated Cost</th>
      <th></th>
      <th class="text-right">$17,500 to $30,300</th>
    </tr>
  </tbody>
</table>

GreatKidsFarm/app/views/report/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#top">Elysian Energy</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Acknowledgements", report_acknowledgement_path %></li>
        <li><%= link_to "Overview", report_overview_path %></li>
        <li><%= link_to "Images", report_images_path %></li>
        <li class="dropdown">
          <a href="#recommendations" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Recommendations<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Part 1: Farm-wide", report_farm_wide_path %></li>
            <li><%= link_to "Part 2: Greenhouse 3", report_greenhouse_3_path %></li>
          </ul>
        </li>
        <li class="nav navbar-nav">
          <a href="#Estimated Costs" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true">Estimated Costs<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Greenhouse 1", report_greenhouse_1_costs_path %></li>
            <li><%= link_to "Greenhouse 2", report_greenhouse_2_costs_path %></li>
            <li><%= link_to "Greenhouse 3", report_greenhouse_3_costs_path %></li>
            <li><%= link_to "Total", report_total_costs_path %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <%= link_to 'Download Report', report_download_path %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>